ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS type         TEXT NOT NULL DEFAULT 'BUY',
    ADD COLUMN IF NOT EXISTS shares       DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS price        DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS fee_currency TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS fee_amount   DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE transactions
    DROP COLUMN IF EXISTS spent_symbol,
    DROP COLUMN IF EXISTS spent_amount,
    DROP COLUMN IF EXISTS gained_symbol,
    DROP COLUMN IF EXISTS gained_amount,
    DROP COLUMN IF EXISTS memo;

ALTER TABLE transactions ALTER COLUMN type DROP DEFAULT;
ALTER TABLE transactions ALTER COLUMN shares DROP DEFAULT;
ALTER TABLE transactions ALTER COLUMN price DROP DEFAULT;
